server:
  port: 5050

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger

json:
  data:
    code-system-entry-url: https://spreadsheets.google.com/feeds/list/1POrP7vIKANlmY1IiUQZf4oXK2dwtgMHAz7vQJeLYMnw/od6/public/values?alt=json

swagger-server:

bonnie-thread-pools:
  thread-pool-configurations:
    - name: threadPoolConversion
      core-pool-size: 50
      max-pool-size: 100
      queue-capacity: 150

mat-api-key: DISABLED

logging:
  level:
    root: DEBUG
    gov.cms.mat: INFO
    org.hl7.fhir.r4.hapi.ctx: WARN
    org.hl7.fhir.r4.hapi.validation: WARN
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %mdc %logger{36}.%M - %msg%n"
  file:
    name: mat-fhir-services.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 1

cache-names: codeSystemEntries
